package loops_math;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MyPC
 */
public class calc2 extends javax.swing.JFrame {

    /**
     * Creates new form calc2
     */
    public calc2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton07 = new javax.swing.JButton();
        jButton06 = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton01 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonequal = new javax.swing.JButton();
        jButtonminus = new javax.swing.JButton();
        jButtonplus = new javax.swing.JButton();
        jButtonmult = new javax.swing.JButton();
        jButtondiv = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        jButtonac = new javax.swing.JButton();
        TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton07.setText("7");
        jButton07.setActionCommand("dig7");
        jButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton06.setText("6");
        jButton06.setActionCommand("dig6");
        jButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton08.setText("8");
        jButton08.setActionCommand("dig8");
        jButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton09.setText("9");
        jButton09.setActionCommand("dig9");
        jButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton02.setText("2");
        jButton02.setActionCommand("dig2");
        jButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton01.setText("1");
        jButton01.setActionCommand("dig1");
        jButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.setActionCommand("dig0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButtonequal.setText("=");
        jButtonequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButtonminus.setText("-");
        jButtonminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButtonplus.setText("+");
        jButtonplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButtonmult.setText("x");
        jButtonmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButtondiv.setText("/");
        jButtondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton03.setText("3");
        jButton03.setActionCommand("dig3");
        jButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButton04.setText("4");
        jButton04.setActionCommand("dig4");

        jButton05.setText("5");
        jButton05.setActionCommand("dig5");
        jButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        jButtonac.setText("AC");
        jButtonac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton01)
                        .addGap(18, 18, 18)
                        .addComponent(jButton02)
                        .addGap(18, 18, 18)
                        .addComponent(jButton03)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonmult, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton0)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonplus)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonminus)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton07)
                                .addGap(18, 18, 18)
                                .addComponent(jButton08)
                                .addGap(18, 18, 18)
                                .addComponent(jButton09))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton04)
                                .addGap(18, 18, 18)
                                .addComponent(jButton05)
                                .addGap(18, 18, 18)
                                .addComponent(jButton06)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtondiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(TF))
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton07)
                    .addComponent(jButton08)
                    .addComponent(jButton09)
                    .addComponent(jButtonac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton05)
                    .addComponent(jButton04)
                    .addComponent(jButton06)
                    .addComponent(jButtondiv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton03)
                    .addComponent(jButtonmult)
                    .addComponent(jButton02)
                    .addComponent(jButton01))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0)
                    .addComponent(jButtonplus)
                    .addComponent(jButtonminus)
                    .addComponent(jButtonequal))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressed
String t= evt.getActionCommand();
String v= TF.getText();



{if (t.equals("dig0"))
TF.setText(v+"0");
else if (t.equals("dig1"))
TF.setText(v+"1");
else if (t.equals("dig2"))
TF.setText(v+"2");
else if (t.equals("dig3"))
TF.setText(v+"3");
else if (t.equals("dig4"))
TF.setText(v+"4");
else if (t.equals("dig5"))
TF.setText(v+"5");
else if (t.equals("dig6"))
TF.setText(v+"6");
else if (t.equals("dig7"))
TF.setText(v+"7");
else if (t.equals("dig8"))
TF.setText(v+"8");
else if (t.equals("dig9"))
TF.setText(v+"9");
else if (t.equals("+"))
TF.setText(v+"+");
else if (t.equals("-"))
TF.setText(v+"-");
else if (t.equals("x"))
TF.setText(v+"x");
else if (t.equals("/"))
TF.setText(v+"/");
else if (t.equals("="))//chk
TF.setText(v+"=");
else if (t.equals("AC"))
TF.setText(v+"");//chk
}
// TODO add your handling code here:
    }//GEN-LAST:event_pressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButtonac;
    private javax.swing.JButton jButtondiv;
    private javax.swing.JButton jButtonequal;
    private javax.swing.JButton jButtonminus;
    private javax.swing.JButton jButtonmult;
    private javax.swing.JButton jButtonplus;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
