package loops_math;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MyPC
 */
public class root extends javax.swing.JFrame {

    /**
     * Creates new form root
     */
    public root() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clrButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        sqButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        cubButton = new javax.swing.JButton();
        cubrtButton = new javax.swing.JButton();
        ansLabel = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        numTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        clrButton.setBackground(new java.awt.Color(153, 255, 255));
        clrButton.setText("Clear");
        clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrButtonActionPerformed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(228, 61, 95));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        sqButton.setBackground(new java.awt.Color(204, 255, 102));
        sqButton.setText("Square");
        sqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqButtonActionPerformed(evt);
            }
        });

        sqrtButton.setBackground(new java.awt.Color(204, 255, 102));
        sqrtButton.setText("Square Root");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });

        cubButton.setBackground(new java.awt.Color(204, 255, 102));
        cubButton.setText("Cube");
        cubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubButtonActionPerformed(evt);
            }
        });

        cubrtButton.setBackground(new java.awt.Color(204, 255, 102));
        cubrtButton.setText("Cube Root");
        cubrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubrtButtonActionPerformed(evt);
            }
        });

        ansLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        numLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        numLabel.setText("Enter number:");

        numTextField.setBackground(new java.awt.Color(153, 255, 255));

        titleLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 0, 204));
        titleLabel.setText("Find Cubes, Cube roots, Squares and Square roots");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(clrButton)
                        .addGap(50, 50, 50)
                        .addComponent(closeButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(sqButton)
                        .addGap(29, 29, 29)
                        .addComponent(sqrtButton)
                        .addGap(18, 18, 18)
                        .addComponent(cubButton)
                        .addGap(29, 29, 29)
                        .addComponent(cubrtButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(numLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ansLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numLabel)
                    .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ansLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqButton)
                    .addComponent(sqrtButton)
                    .addComponent(cubButton)
                    .addComponent(cubrtButton))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clrButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrButtonActionPerformed
        numTextField.setText(" ");
        ansLabel.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_clrButtonActionPerformed

    private void cubrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubrtButtonActionPerformed
        double x,y;
        x= Double.parseDouble(numTextField.getText());
        y= Math.pow(x,0.33);
        ansLabel.setText("The answer is: "+y);        // TODO add your handling code here:
    }//GEN-LAST:event_cubrtButtonActionPerformed

    private void cubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubButtonActionPerformed
        Float x,y;
        x= Float.parseFloat(numTextField.getText());
        y= x*x*x;
        ansLabel.setText("The answer is: "+y);        // TODO add your handling code here:
    }//GEN-LAST:event_cubButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        double x,y;
        x= Double.parseDouble(numTextField.getText());
        y= Math.pow(x,0.5) ;
        ansLabel.setText("The answer is: "+y);        // TODO add your handling code here:
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void sqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqButtonActionPerformed
        float x,y;
        x= Float.parseFloat(numTextField.getText());
        y= x*x;
        ansLabel.setText("The answer is: "+y);

        // TODO add your handling code here:
    }//GEN-LAST:event_sqButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new root().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton clrButton;
    private javax.swing.JButton cubButton;
    private javax.swing.JButton cubrtButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numLabel;
    private javax.swing.JTextField numTextField;
    private javax.swing.JButton sqButton;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
